export default {
	CONFIG_GAME_BOARD: 'CONFIG_GAME_BOARD',
	ALLOCATE_BOMB: 'ALLOCATE_BOMB',
	ALLOCATE_ADJACENT_BOMBS: 'ALLOCATE_ADJACENT_BOMBS',
	REVEAL_CELL: 'REVEAL_CELL',
	MARK_CELL: 'MARK_CELL',
	SET_MARK: 'SET_MARK',
	INCREMENT_FLAGS: 'INCREMENT_FLAGS',
	DECREMENT_FLAGS: 'DECREMENT_FLAGS',
	START_GAME: 'START_GAME',
	GAME_OVER: 'GAME_OVER',
	RESET: 'RESET',
	INCREMENT_TIME: 'INCREMENT_TIME',
};
