export default {
	INIT_GAME_BOARD: 'INIT_GAME_BOARD',
  ALLOCATE_BOMB: 'ALLOCATE_BOMB',
  ALLOCATE_ADJACENT_BOMBS: 'ALLOCATE_ADJACENT_BOMBS',
  REVEAL_CELL: 'REVEAL_CELL',
  MARK_CELL: 'MARK_CELL', 
  GAME_OVER: 'GAME_OVER'
};